### ISSUE TITLE
List all topics of a course on course page

### ISSUE THREAD

**Issue by BernhardKonrad** [wayneyu/merapp#22]
@wayneyu and I started this at our previous meeting.

**Comment by BernhardKonrad** [comment]
Here is how far I got. @wayneyu, could you please have a look at the `HELP` at [line 479 of the Questions controller](https://github.com/wayneyu/merapp/commit/9dce6706513e6a494f6395f2c30990864a89d4a4#diff-ad34a671f2bae1f7580de3fb6c1cf379R479)?

**Comment by wayneyu** [comment]
Fixed in 1090bca94899ff2ba28388b5aeee0124a0c308db.

The println statement inside map() of Future of list of topics is only executed when the list has successfully formed.

I also changed the println to Logger.info. We should use the logger instead of system.out.print.

For the 2nd help, the views.html.course needed to be cleaned and recompiled cause it's a method in the target directory.

**Comment by BernhardKonrad** [comment]
Fantastic, thank you! That makes much more sense now!
To correctly calculate the percentages on the course page I would need the total number of questions, ie, length of the list `topics` (not `list_of_topics`). How would I pass that on to `views.html.course`?

**Comment by wayneyu** [comment]
I would define the length in course.scala.html: @topics_length = @{topics.size}

**Comment by BernhardKonrad** [comment]
Hi. You're right, length of `list_of_topics` can be obtained that way. However, I need the total number of questions, hence the length of the list `topics` (which is a Future BSONformat).

**Comment by wayneyu** [comment]
I see. Then do:

```
val nlist = topics.map{ ts => ts.size }
...

val res = for {
      e <- exams
      t <- list_of_topics
      nlist <- nlist
    } yield (e, t, nlist)

res.map{ case(exams, topics, nlist) => ...
```

**Comment by BernhardKonrad** [comment]
Thank you, that works! This shows that I didn't understand the `map` function...
